name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: IPFS Pinata deploy GitHub action
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
        with:
          path: ./
          pin-name: "my-decentralized-website" 
          pinata-api-key: ${{ secrets.PINATA_API_KEY }} 
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
          remove-old: true 
          verbose: true  


